name: Generate Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'  # This will run daily at midnight UTC
  workflow_dispatch:  # This allows you to manually trigger the action

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Contribution Graph
      uses: Platane/snk@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's token for authentication
        output: github-contribution-grid-snake.svg  # Output filename for the graph

    - name: Check if the file exists and commit
      run: |
        if [ -f github-contribution-grid-snake.svg ]; then
          git config --global user.name "IanGichengo"
          git config --global user.email "iangatimu6@gmail.com"  # Fixed email address
          git add github-contribution-grid-snake.svg
          git commit -m "Update contribution graph"
          git push
        else
          echo "No contribution graph file generated."
        fi
