name: Generate Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'  # This will run daily at midnight UTC
  workflow_dispatch:  # This allows you to manually trigger the action

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Contribution Graph
      uses: Platane/snk@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's token for authentication
        output: github-contribution-grid-snake.svg  # Output filename for the graph
      continue-on-error: true

    - name: Commit & push generated graph
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add github-contribution-grid-snake.svg  # Add the generated graph
        git commit -m "Update contribution graph"  # Commit the change
        git push  # Push the change back to the repository
